### ISSUE TITLE
AODP Viewer

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1743]
Add a basic viewer for AODP result viewing:

#### Preparation
1. Use latest commits from release-4.0.0 and restart server.
2. Import [_Puccinia_ reference](https://github.com/virtool/virtool/files/4264245/puccinia.json.gz).
3. Create paired-end amplicon samples using special data files provided.

#### Results Structure
- detail
  - results
    - result/OTU
      - isolate
        - sequence
          - hit

#### Tasks
- [x] extend `formatAODPData()` @ `src/js/analyses/utils.js`

  This function formats an AODP analysis result that is returned from a API request. You can use `console.log` to see what the incoming data looks like

  - For each item in `results`, add an array of all `identity` values of hits nested under the result item; call it `identities`. This will be used later to filter the data
  - For each isolate under each item add a similar `identities` field. This and the above operation can be combined to minimize computation.

#### Viewer
The viewer for AODP is results already has a very basic working setup.
- [x] change `hit` prop in `AODPDetail` to `result`
- [x] populate `AODPDetail` using data from `hit` prop
- [x] add a toolbar like those for pathoscope and NuVs; does not need to be functional yet
  - search input
  - number type inputs for adjusting "Minimum Identity"; this will filter the results
    - [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)
    - range should be `0.5` - `1.0` with `0.01` increments
    - could also try using this: https://reacttraining.com/reach-ui/slider
